
imagePullSecrets: []

yurtControllerManager:
  replicaCount: 1
  tolerations: []
  image:
    registry: docker.io
    repository: openyurt/yurt-controller-manager
    pullPolicy: IfNotPresent
    tag: v1.0.0
  service:
    type: ClusterIP
    port: 80

yurtTunnelAgent:
  replicaCount: 1
  tolerations: []
  parameters:
    tunnelserverAddr: ""
  image:
    registry: docker.io
    repository: openyurt/yurt-tunnel-agent
    pullPolicy: IfNotPresent
    tag: v1.0.0

yurtTunnelServer:
  replicaCount: 1
  tolerations: []
  parameters:
    certDnsNames: ""
    certIps: ""
  image:
    registry: docker.io
    repository: openyurt/yurt-tunnel-server
    pullPolicy: IfNotPresent
    tag: v1.0.0

poolCoordinator:
  apiserverSecurePort: 10270
  apiserverImage:
    registry: docker.io
    repository: google_containers/kube-apiserver
    pullPolicy: IfNotPresent
    tag: v1.20.0
  apiserverResources:
    requests:
      cpu: 250m
  serviceClusterIPRange: 10.96.0.0/12
  etcdPort: 12379
  etcdMetricPort: 12381
  etcdImage:
    registry: docker.io
    repository: google_containers/etcd
    pullPolicy: IfNotPresent
    tag: 3.5.0-0
  etcdResources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
